# Generated by Django 3.0.7 on 2020-06-24 08:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('license_no', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('hire_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('email', models.CharField(max_length=255)),
                ('id_no', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
            },
        ),
    ]
