# Generated by Django 3.0.7 on 2020-06-22 16:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('client', '0001_initial'),
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourneyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Journey Type',
                'verbose_name_plural': 'Journey Types',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('travel_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('vehicle_no', models.CharField(max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='client.Client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='company.Company')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='driver.Driver')),
                ('journey_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trip.JourneyType')),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trip',
            },
        ),
    ]
