# Generated by Django 3.0.7 on 2020-06-24 12:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0002_auto_20200624_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourneyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Journey Type',
                'verbose_name_plural': 'Journey Types',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('travel_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('vehicle_no', models.CharField(max_length=20)),
                ('start_mileage', models.IntegerField(null=True)),
                ('end_mileage', models.IntegerField(null=True)),
                ('start_time', models.DateTimeField(blank=True)),
                ('end_time', models.DateTimeField(blank=True)),
                ('client', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='company', chained_model_field='company', on_delete=django.db.models.deletion.CASCADE, to='client.Client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='company.Company')),
                ('driver', models.ForeignKey(limit_choices_to={'groups__pk': 1}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('journey_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trip.JourneyType')),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trip',
            },
        ),
    ]
