# Generated by Django 3.0.7 on 2020-06-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_auto_20200624_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trip_status',
            field=models.CharField(default='created', max_length=20),
        ),
    ]
